// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ActConcurrentNodeColumns holds the columns for the "act_concurrent_node" table.
	ActConcurrentNodeColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "proc_inst_id", Type: field.TypeInt64},
		{Name: "proc_def_id", Type: field.TypeInt64},
		{Name: "node_id", Type: field.TypeString, Size: 50},
		{Name: "node_info", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "prev_id", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "next_id", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "state", Type: field.TypeInt32, Nullable: true},
		{Name: "is_del", Type: field.TypeInt32, Nullable: true, Default: 0},
		{Name: "create_time", Type: field.TypeTime, Nullable: true},
		{Name: "update_time", Type: field.TypeTime, Nullable: true},
	}
	// ActConcurrentNodeTable holds the schema information for the "act_concurrent_node" table.
	ActConcurrentNodeTable = &schema.Table{
		Name:       "act_concurrent_node",
		Columns:    ActConcurrentNodeColumns,
		PrimaryKey: []*schema.Column{ActConcurrentNodeColumns[0]},
	}
	// ActExecutionColumns holds the columns for the "act_execution" table.
	ActExecutionColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "proc_inst_id", Type: field.TypeInt64},
		{Name: "proc_def_id", Type: field.TypeInt64},
		{Name: "node_infos", Type: field.TypeString, Nullable: true, Size: 5000},
		{Name: "start_time", Type: field.TypeTime, Nullable: true},
		{Name: "is_del", Type: field.TypeInt32, Nullable: true, Default: 0},
		{Name: "create_time", Type: field.TypeTime, Nullable: true},
		{Name: "update_time", Type: field.TypeTime, Nullable: true},
	}
	// ActExecutionTable holds the schema information for the "act_execution" table.
	ActExecutionTable = &schema.Table{
		Name:       "act_execution",
		Columns:    ActExecutionColumns,
		PrimaryKey: []*schema.Column{ActExecutionColumns[0]},
	}
	// ActIdentityLinkColumns holds the columns for the "act_identity_link" table.
	ActIdentityLinkColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "user_id", Type: field.TypeInt64, Nullable: true},
		{Name: "user_name", Type: field.TypeString, Nullable: true, Size: 50},
		{Name: "step", Type: field.TypeInt32, Nullable: true},
		{Name: "proc_inst_id", Type: field.TypeInt64},
		{Name: "target_id", Type: field.TypeInt64, Nullable: true},
		{Name: "comment", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "task_id", Type: field.TypeInt64},
		{Name: "result", Type: field.TypeInt32, Nullable: true},
		{Name: "create_time", Type: field.TypeTime, Nullable: true},
		{Name: "is_del", Type: field.TypeInt32, Nullable: true, Default: 0},
		{Name: "is_deal", Type: field.TypeInt32, Nullable: true, Default: 0},
		{Name: "update_time", Type: field.TypeTime, Nullable: true},
	}
	// ActIdentityLinkTable holds the schema information for the "act_identity_link" table.
	ActIdentityLinkTable = &schema.Table{
		Name:       "act_identity_link",
		Columns:    ActIdentityLinkColumns,
		PrimaryKey: []*schema.Column{ActIdentityLinkColumns[0]},
	}
	// ActProcDefColumns holds the columns for the "act_proc_def" table.
	ActProcDefColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString, Nullable: true, Size: 200},
		{Name: "code", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "version", Type: field.TypeInt32, Nullable: true},
		{Name: "resource", Type: field.TypeString, Size: 10000},
		{Name: "create_user_id", Type: field.TypeInt64, Nullable: true},
		{Name: "create_user_name", Type: field.TypeString, Nullable: true, Size: 50},
		{Name: "create_time", Type: field.TypeTime, Nullable: true},
		{Name: "target_id", Type: field.TypeInt64, Nullable: true},
		{Name: "form_id", Type: field.TypeInt64, Nullable: true},
		{Name: "form_name", Type: field.TypeString, Nullable: true, Size: 50},
		{Name: "app_id", Type: field.TypeInt64, Nullable: true},
		{Name: "app_name", Type: field.TypeString, Nullable: true, Size: 50},
		{Name: "remain_hours", Type: field.TypeInt32, Nullable: true, Default: 0},
		{Name: "is_del", Type: field.TypeInt32, Nullable: true, Default: 0},
		{Name: "is_active", Type: field.TypeInt32, Nullable: true, Default: 0},
		{Name: "update_time", Type: field.TypeTime, Nullable: true},
		{Name: "del_time", Type: field.TypeTime, Nullable: true},
		{Name: "del_user_id", Type: field.TypeInt64, Nullable: true},
		{Name: "update_user_id", Type: field.TypeInt64, Nullable: true},
	}
	// ActProcDefTable holds the schema information for the "act_proc_def" table.
	ActProcDefTable = &schema.Table{
		Name:       "act_proc_def",
		Columns:    ActProcDefColumns,
		PrimaryKey: []*schema.Column{ActProcDefColumns[0]},
	}
	// ActProcInstColumns holds the columns for the "act_proc_inst" table.
	ActProcInstColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "proc_def_id", Type: field.TypeInt64},
		{Name: "title", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "code", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "target_id", Type: field.TypeInt64, Nullable: true},
		{Name: "node_id", Type: field.TypeString, Nullable: true, Size: 50},
		{Name: "task_id", Type: field.TypeInt64, Nullable: true},
		{Name: "start_time", Type: field.TypeTime, Nullable: true},
		{Name: "end_time", Type: field.TypeTime, Nullable: true},
		{Name: "start_user_id", Type: field.TypeInt64, Nullable: true},
		{Name: "start_user_name", Type: field.TypeString, Nullable: true, Size: 50},
		{Name: "is_finished", Type: field.TypeInt32, Nullable: true, Default: 0},
		{Name: "state", Type: field.TypeInt32, Nullable: true},
		{Name: "data_id", Type: field.TypeInt64, Nullable: true},
		{Name: "is_del", Type: field.TypeInt32, Nullable: true, Default: 0},
		{Name: "create_time", Type: field.TypeTime, Nullable: true},
		{Name: "remain_hours", Type: field.TypeInt32, Nullable: true},
		{Name: "update_time", Type: field.TypeTime, Nullable: true},
		{Name: "flow_type", Type: field.TypeInt32, Nullable: true, Default: 1},
		{Name: "remark", Type: field.TypeString, Nullable: true, Size: 1000},
		{Name: "del_time", Type: field.TypeTime, Nullable: true},
		{Name: "del_user_id", Type: field.TypeInt64, Nullable: true},
		{Name: "update_user_id", Type: field.TypeInt64, Nullable: true},
	}
	// ActProcInstTable holds the schema information for the "act_proc_inst" table.
	ActProcInstTable = &schema.Table{
		Name:       "act_proc_inst",
		Columns:    ActProcInstColumns,
		PrimaryKey: []*schema.Column{ActProcInstColumns[0]},
	}
	// ActTaskColumns holds the columns for the "act_task" table.
	ActTaskColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "node_id", Type: field.TypeString, Nullable: true, Size: 50},
		{Name: "level", Type: field.TypeInt32, Nullable: true},
		{Name: "step", Type: field.TypeInt32, Nullable: true},
		{Name: "proc_inst_id", Type: field.TypeInt64},
		{Name: "create_time", Type: field.TypeTime, Nullable: true},
		{Name: "claim_time", Type: field.TypeTime, Nullable: true},
		{Name: "member_approver", Type: field.TypeString, Nullable: true, Size: 5000},
		{Name: "agree_approver", Type: field.TypeString, Nullable: true, Size: 2000},
		{Name: "is_finished", Type: field.TypeInt32, Nullable: true, Default: 0},
		{Name: "mode", Type: field.TypeString, Nullable: true, Default: "or"},
		{Name: "is_del", Type: field.TypeInt32, Nullable: true, Default: 0},
		{Name: "update_time", Type: field.TypeTime, Nullable: true},
	}
	// ActTaskTable holds the schema information for the "act_task" table.
	ActTaskTable = &schema.Table{
		Name:       "act_task",
		Columns:    ActTaskColumns,
		PrimaryKey: []*schema.Column{ActTaskColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ActConcurrentNodeTable,
		ActExecutionTable,
		ActIdentityLinkTable,
		ActProcDefTable,
		ActProcInstTable,
		ActTaskTable,
	}
)

func init() {
	ActConcurrentNodeTable.Annotation = &entsql.Annotation{
		Table: "act_concurrent_node",
	}
	ActExecutionTable.Annotation = &entsql.Annotation{
		Table: "act_execution",
	}
	ActIdentityLinkTable.Annotation = &entsql.Annotation{
		Table: "act_identity_link",
	}
	ActProcDefTable.Annotation = &entsql.Annotation{
		Table: "act_proc_def",
	}
	ActProcInstTable.Annotation = &entsql.Annotation{
		Table: "act_proc_inst",
	}
	ActTaskTable.Annotation = &entsql.Annotation{
		Table: "act_task",
	}
}
