// Code generated by entc, DO NOT EDIT.

package nodenotifiers

import (
	"time"
)

const (
	// Label holds the string label denoting the nodenotifiers type in the database.
	Label = "nodenotifiers"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the userid field in the database.
	FieldUserID = "user_id"
	// FieldProcInstID holds the string denoting the procinstid field in the database.
	FieldProcInstID = "proc_inst_id"
	// FieldTargetID holds the string denoting the targetid field in the database.
	FieldTargetID = "target_id"
	// FieldComment holds the string denoting the comment field in the database.
	FieldComment = "comment"
	// FieldCreateTime holds the string denoting the createtime field in the database.
	FieldCreateTime = "create_time"
	// FieldIsPermit holds the string denoting the ispermit field in the database.
	FieldIsPermit = "is_permit"
	// FieldIsDeal holds the string denoting the isdeal field in the database.
	FieldIsDeal = "is_deal"
	// FieldUpdateTime holds the string denoting the updatetime field in the database.
	FieldUpdateTime = "update_time"
	// FieldCreateUser holds the string denoting the createuser field in the database.
	FieldCreateUser = "create_user"
	// FieldUpdateUser holds the string denoting the updateuser field in the database.
	FieldUpdateUser = "update_user"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// Table holds the table name of the nodenotifiers in the database.
	Table = "wflow_node_notifiers"
)

// Columns holds all SQL columns for nodenotifiers fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldProcInstID,
	FieldTargetID,
	FieldComment,
	FieldCreateTime,
	FieldIsPermit,
	FieldIsDeal,
	FieldUpdateTime,
	FieldCreateUser,
	FieldUpdateUser,
	FieldVersion,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CommentValidator is a validator for the "comment" field. It is called by the builders before save.
	CommentValidator func(string) error
	// DefaultCreateTime holds the default value on creation for the "createTime" field.
	DefaultCreateTime time.Time
	// DefaultIsPermit holds the default value on creation for the "isPermit" field.
	DefaultIsPermit uint64
	// DefaultIsDeal holds the default value on creation for the "isDeal" field.
	DefaultIsDeal uint64
	// DefaultUpdateTime holds the default value on creation for the "updateTime" field.
	DefaultUpdateTime time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uint64
)
