// Code generated by goctl. DO NOT EDIT!
// Source: act.proto

package act

import (
	"context"

	"act/rpc/ms"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ExecutionReply    = ms.ExecutionReply
	ExecutionReq      = ms.ExecutionReq
	IdentityLinkReply = ms.IdentityLinkReply
	IdentityLinkReq   = ms.IdentityLinkReq
	ProcDefReply      = ms.ProcDefReply
	ProcDefReq        = ms.ProcDefReq
	ProcInstReply     = ms.ProcInstReply
	ProcInstReq       = ms.ProcInstReq
	TaskReply         = ms.TaskReply
	TaskReq           = ms.TaskReq

	Act interface {
		SaveProcDef(ctx context.Context, in *ProcDefReq, opts ...grpc.CallOption) (*ProcDefReply, error)
		SaveProcInst(ctx context.Context, in *ProcInstReq, opts ...grpc.CallOption) (*ProcInstReply, error)
		SaveExecution(ctx context.Context, in *ExecutionReq, opts ...grpc.CallOption) (*ExecutionReply, error)
		SaveTask(ctx context.Context, in *TaskReq, opts ...grpc.CallOption) (*TaskReply, error)
		SaveIdentityLink(ctx context.Context, in *IdentityLinkReq, opts ...grpc.CallOption) (*IdentityLinkReply, error)
	}

	defaultAct struct {
		cli zrpc.Client
	}
)

func NewAct(cli zrpc.Client) Act {
	return &defaultAct{
		cli: cli,
	}
}

func (m *defaultAct) SaveProcDef(ctx context.Context, in *ProcDefReq, opts ...grpc.CallOption) (*ProcDefReply, error) {
	client := ms.NewActClient(m.cli.Conn())
	return client.SaveProcDef(ctx, in, opts...)
}

func (m *defaultAct) SaveProcInst(ctx context.Context, in *ProcInstReq, opts ...grpc.CallOption) (*ProcInstReply, error) {
	client := ms.NewActClient(m.cli.Conn())
	return client.SaveProcInst(ctx, in, opts...)
}

func (m *defaultAct) SaveExecution(ctx context.Context, in *ExecutionReq, opts ...grpc.CallOption) (*ExecutionReply, error) {
	client := ms.NewActClient(m.cli.Conn())
	return client.SaveExecution(ctx, in, opts...)
}

func (m *defaultAct) SaveTask(ctx context.Context, in *TaskReq, opts ...grpc.CallOption) (*TaskReply, error) {
	client := ms.NewActClient(m.cli.Conn())
	return client.SaveTask(ctx, in, opts...)
}

func (m *defaultAct) SaveIdentityLink(ctx context.Context, in *IdentityLinkReq, opts ...grpc.CallOption) (*IdentityLinkReply, error) {
	client := ms.NewActClient(m.cli.Conn())
	return client.SaveIdentityLink(ctx, in, opts...)
}
