// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wflow/kernel/ent/nodedetails"
	"go-wflow/kernel/ent/predicate"
	"math"

	"github.com/qkbyte/ent/dialect/sql"
	"github.com/qkbyte/ent/dialect/sql/sqlgraph"
	"github.com/qkbyte/ent/schema/field"
)

// NodeDetailsQuery is the builder for querying NodeDetails entities.
type NodeDetailsQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.NodeDetails
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the NodeDetailsQuery builder.
func (ndq *NodeDetailsQuery) Where(ps ...predicate.NodeDetails) *NodeDetailsQuery {
	ndq.predicates = append(ndq.predicates, ps...)
	return ndq
}

// Limit adds a limit step to the query.
func (ndq *NodeDetailsQuery) Limit(limit int) *NodeDetailsQuery {
	ndq.limit = &limit
	return ndq
}

// Offset adds an offset step to the query.
func (ndq *NodeDetailsQuery) Offset(offset int) *NodeDetailsQuery {
	ndq.offset = &offset
	return ndq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ndq *NodeDetailsQuery) Unique(unique bool) *NodeDetailsQuery {
	ndq.unique = &unique
	return ndq
}

// Order adds an order step to the query.
func (ndq *NodeDetailsQuery) Order(o ...OrderFunc) *NodeDetailsQuery {
	ndq.order = append(ndq.order, o...)
	return ndq
}

// First returns the first NodeDetails entity from the query.
// Returns a *NotFoundError when no NodeDetails was found.
func (ndq *NodeDetailsQuery) First(ctx context.Context) (*NodeDetails, error) {
	nodes, err := ndq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{nodedetails.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ndq *NodeDetailsQuery) FirstX(ctx context.Context) *NodeDetails {
	node, err := ndq.First(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// FirstID returns the first NodeDetails ID from the query.
// Returns a *NotFoundError when no NodeDetails ID was found.
func (ndq *NodeDetailsQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = ndq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{nodedetails.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ndq *NodeDetailsQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := ndq.FirstID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// Only returns a single NodeDetails entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one NodeDetails entity is found.
// Returns a *NotFoundError when no NodeDetails entities are found.
func (ndq *NodeDetailsQuery) Only(ctx context.Context) (*NodeDetails, error) {
	nodes, err := ndq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{nodedetails.Label}
	default:
		return nil, &NotSingularError{nodedetails.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ndq *NodeDetailsQuery) OnlyX(ctx context.Context) *NodeDetails {
	node, err := ndq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only NodeDetails ID in the query.
// Returns a *NotSingularError when more than one NodeDetails ID is found.
// Returns a *NotFoundError when no entities are found.
func (ndq *NodeDetailsQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = ndq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{nodedetails.Label}
	default:
		err = &NotSingularError{nodedetails.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ndq *NodeDetailsQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := ndq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of NodeDetailsSlice.
func (ndq *NodeDetailsQuery) All(ctx context.Context) ([]*NodeDetails, error) {
	if err := ndq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ndq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ndq *NodeDetailsQuery) AllX(ctx context.Context) []*NodeDetails {
	nodes, err := ndq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of NodeDetails IDs.
func (ndq *NodeDetailsQuery) IDs(ctx context.Context) ([]uint64, error) {
	var ids []uint64
	if err := ndq.Select(nodedetails.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ndq *NodeDetailsQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := ndq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ndq *NodeDetailsQuery) Count(ctx context.Context) (int, error) {
	if err := ndq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ndq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ndq *NodeDetailsQuery) CountX(ctx context.Context) int {
	count, err := ndq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ndq *NodeDetailsQuery) Exist(ctx context.Context) (bool, error) {
	if err := ndq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ndq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ndq *NodeDetailsQuery) ExistX(ctx context.Context) bool {
	exist, err := ndq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the NodeDetailsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ndq *NodeDetailsQuery) Clone() *NodeDetailsQuery {
	if ndq == nil {
		return nil
	}
	return &NodeDetailsQuery{
		config:     ndq.config,
		limit:      ndq.limit,
		offset:     ndq.offset,
		order:      append([]OrderFunc{}, ndq.order...),
		predicates: append([]predicate.NodeDetails{}, ndq.predicates...),
		// clone intermediate query.
		sql:    ndq.sql.Clone(),
		path:   ndq.path,
		unique: ndq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ProcInstID uint64 `json:"procInstID"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.NodeDetails.Query().
//		GroupBy(nodedetails.FieldProcInstID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (ndq *NodeDetailsQuery) GroupBy(field string, fields ...string) *NodeDetailsGroupBy {
	group := &NodeDetailsGroupBy{config: ndq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ndq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ndq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ProcInstID uint64 `json:"procInstID"`
//	}
//
//	client.NodeDetails.Query().
//		Select(nodedetails.FieldProcInstID).
//		Scan(ctx, &v)
//
func (ndq *NodeDetailsQuery) Select(fields ...string) *NodeDetailsSelect {
	ndq.fields = append(ndq.fields, fields...)
	return &NodeDetailsSelect{NodeDetailsQuery: ndq}
}

func (ndq *NodeDetailsQuery) prepareQuery(ctx context.Context) error {
	for _, f := range ndq.fields {
		if !nodedetails.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: 错误字段 %q 在查询中", f)}
		}
	}
	if ndq.path != nil {
		prev, err := ndq.path(ctx)
		if err != nil {
			return err
		}
		ndq.sql = prev
	}
	return nil
}

func (ndq *NodeDetailsQuery) sqlAll(ctx context.Context) ([]*NodeDetails, error) {
	var (
		nodes = []*NodeDetails{}
		_spec = ndq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &NodeDetails{config: ndq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign调用的值而不调用ScanValue")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, ndq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ndq *NodeDetailsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ndq.querySpec()
	_spec.Node.Columns = ndq.fields
	if len(ndq.fields) > 0 {
		_spec.Unique = ndq.unique != nil && *ndq.unique
	}
	return sqlgraph.CountNodes(ctx, ndq.driver, _spec)
}

func (ndq *NodeDetailsQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := ndq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: 检查是否存在: %w", err)
	}
	return n > 0, nil
}

func (ndq *NodeDetailsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   nodedetails.Table,
			Columns: nodedetails.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: nodedetails.FieldID,
			},
		},
		From:   ndq.sql,
		Unique: true,
	}
	if unique := ndq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := ndq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, nodedetails.FieldID)
		for i := range fields {
			if fields[i] != nodedetails.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ndq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ndq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ndq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ndq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ndq *NodeDetailsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ndq.driver.Dialect())
	t1 := builder.Table(nodedetails.Table)
	columns := ndq.fields
	if len(columns) == 0 {
		columns = nodedetails.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ndq.sql != nil {
		selector = ndq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ndq.unique != nil && *ndq.unique {
		selector.Distinct()
	}
	for _, p := range ndq.predicates {
		p(selector)
	}
	for _, p := range ndq.order {
		p(selector)
	}
	if offset := ndq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ndq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// NodeDetailsGroupBy is the group-by builder for NodeDetails entities.
type NodeDetailsGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ndgb *NodeDetailsGroupBy) Aggregate(fns ...AggregateFunc) *NodeDetailsGroupBy {
	ndgb.fns = append(ndgb.fns, fns...)
	return ndgb
}

// Scan applies the group-by query and scans the result into the given value.
func (ndgb *NodeDetailsGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := ndgb.path(ctx)
	if err != nil {
		return err
	}
	ndgb.sql = query
	return ndgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ndgb *NodeDetailsGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := ndgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (ndgb *NodeDetailsGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(ndgb.fields) > 1 {
		return nil, errors.New("ent: NodeDetailsGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := ndgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ndgb *NodeDetailsGroupBy) StringsX(ctx context.Context) []string {
	v, err := ndgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ndgb *NodeDetailsGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ndgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nodedetails.Label}
	default:
		err = fmt.Errorf("ent: NodeDetailsGroupBy.Strings 返回结果集不唯一,数量%d", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ndgb *NodeDetailsGroupBy) StringX(ctx context.Context) string {
	v, err := ndgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (ndgb *NodeDetailsGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(ndgb.fields) > 1 {
		return nil, errors.New("ent: NodeDetailsGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := ndgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ndgb *NodeDetailsGroupBy) IntsX(ctx context.Context) []int {
	v, err := ndgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ndgb *NodeDetailsGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ndgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nodedetails.Label}
	default:
		err = fmt.Errorf("ent: NodeDetailsGroupBy.Ints 返回结果集不唯一,数量%d", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ndgb *NodeDetailsGroupBy) IntX(ctx context.Context) int {
	v, err := ndgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Uint64s returns list of uint64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (ndgb *NodeDetailsGroupBy) Uint64s(ctx context.Context) ([]uint64, error) {
	if len(ndgb.fields) > 1 {
		return nil, errors.New("ent: NodeDetailsGroupBy.Uint64s is not achievable when grouping more than 1 field")
	}
	var v []uint64
	if err := ndgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Uint64sX is like Uint64s, but panics if an error occurs.
func (ndgb *NodeDetailsGroupBy) Uint64sX(ctx context.Context) []uint64 {
	v, err := ndgb.Uint64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Uint64 returns a single uint64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ndgb *NodeDetailsGroupBy) Uint64(ctx context.Context) (_ uint64, err error) {
	var v []uint64
	if v, err = ndgb.Uint64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nodedetails.Label}
	default:
		err = fmt.Errorf("ent: NodeDetailsGroupBy.Uint64s 返回结果集不唯一,数量%d", len(v))
	}
	return
}

// Uint64X is like Uint64, but panics if an error occurs.
func (ndgb *NodeDetailsGroupBy) Uint64X(ctx context.Context) uint64 {
	v, err := ndgb.Uint64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (ndgb *NodeDetailsGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(ndgb.fields) > 1 {
		return nil, errors.New("ent: NodeDetailsGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := ndgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ndgb *NodeDetailsGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := ndgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ndgb *NodeDetailsGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ndgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nodedetails.Label}
	default:
		err = fmt.Errorf("ent: NodeDetailsGroupBy.Float64s 返回结果集不唯一,数量%d", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ndgb *NodeDetailsGroupBy) Float64X(ctx context.Context) float64 {
	v, err := ndgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (ndgb *NodeDetailsGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(ndgb.fields) > 1 {
		return nil, errors.New("ent: NodeDetailsGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := ndgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ndgb *NodeDetailsGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := ndgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ndgb *NodeDetailsGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ndgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nodedetails.Label}
	default:
		err = fmt.Errorf("ent: NodeDetailsGroupBy.Bools 返回结果集不唯一,数量%d", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ndgb *NodeDetailsGroupBy) BoolX(ctx context.Context) bool {
	v, err := ndgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ndgb *NodeDetailsGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range ndgb.fields {
		if !nodedetails.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("错误的字段 %q 对于分组字段", f)}
		}
	}
	selector := ndgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ndgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ndgb *NodeDetailsGroupBy) sqlQuery() *sql.Selector {
	selector := ndgb.sql.Select()
	aggregation := make([]string, 0, len(ndgb.fns))
	for _, fn := range ndgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(ndgb.fields)+len(ndgb.fns))
		for _, f := range ndgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(ndgb.fields...)...)
}

// NodeDetailsSelect is the builder for selecting fields of NodeDetails entities.
type NodeDetailsSelect struct {
	*NodeDetailsQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (nds *NodeDetailsSelect) Scan(ctx context.Context, v interface{}) error {
	if err := nds.prepareQuery(ctx); err != nil {
		return err
	}
	nds.sql = nds.NodeDetailsQuery.sqlQuery(ctx)
	return nds.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (nds *NodeDetailsSelect) ScanX(ctx context.Context, v interface{}) {
	if err := nds.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (nds *NodeDetailsSelect) Strings(ctx context.Context) ([]string, error) {
	if len(nds.fields) > 1 {
		return nil, errors.New("ent: NodeDetailsSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := nds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (nds *NodeDetailsSelect) StringsX(ctx context.Context) []string {
	v, err := nds.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (nds *NodeDetailsSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = nds.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nodedetails.Label}
	default:
		err = fmt.Errorf("ent: NodeDetailsSelect.Strings 返回结果不唯一,数量 %d", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (nds *NodeDetailsSelect) StringX(ctx context.Context) string {
	v, err := nds.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (nds *NodeDetailsSelect) Ints(ctx context.Context) ([]int, error) {
	if len(nds.fields) > 1 {
		return nil, errors.New("ent: NodeDetailsSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := nds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (nds *NodeDetailsSelect) IntsX(ctx context.Context) []int {
	v, err := nds.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (nds *NodeDetailsSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = nds.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nodedetails.Label}
	default:
		err = fmt.Errorf("ent: NodeDetailsSelect.Ints 返回结果不唯一,数量 %d", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (nds *NodeDetailsSelect) IntX(ctx context.Context) int {
	v, err := nds.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Uint64s returns list of uint64s from a selector. It is only allowed when selecting one field.
func (nds *NodeDetailsSelect) Uint64s(ctx context.Context) ([]uint64, error) {
	if len(nds.fields) > 1 {
		return nil, errors.New("ent: NodeDetailsSelect.Uint64s is not achievable when selecting more than 1 field")
	}
	var v []uint64
	if err := nds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Uint64sX is like Uint64s, but panics if an error occurs.
func (nds *NodeDetailsSelect) Uint64sX(ctx context.Context) []uint64 {
	v, err := nds.Uint64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Uint64 returns a single uint64 from a selector. It is only allowed when selecting one field.
func (nds *NodeDetailsSelect) Uint64(ctx context.Context) (_ uint64, err error) {
	var v []uint64
	if v, err = nds.Uint64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nodedetails.Label}
	default:
		err = fmt.Errorf("ent: NodeDetailsSelect.Uint64s 返回结果不唯一,数量 %d", len(v))
	}
	return
}

// Uint64X is like Uint64, but panics if an error occurs.
func (nds *NodeDetailsSelect) Uint64X(ctx context.Context) uint64 {
	v, err := nds.Uint64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (nds *NodeDetailsSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(nds.fields) > 1 {
		return nil, errors.New("ent: NodeDetailsSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := nds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (nds *NodeDetailsSelect) Float64sX(ctx context.Context) []float64 {
	v, err := nds.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (nds *NodeDetailsSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = nds.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nodedetails.Label}
	default:
		err = fmt.Errorf("ent: NodeDetailsSelect.Float64s 返回结果不唯一,数量 %d", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (nds *NodeDetailsSelect) Float64X(ctx context.Context) float64 {
	v, err := nds.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (nds *NodeDetailsSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(nds.fields) > 1 {
		return nil, errors.New("ent: NodeDetailsSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := nds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (nds *NodeDetailsSelect) BoolsX(ctx context.Context) []bool {
	v, err := nds.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (nds *NodeDetailsSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = nds.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nodedetails.Label}
	default:
		err = fmt.Errorf("ent: NodeDetailsSelect.Bools 返回结果不唯一,数量 %d", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (nds *NodeDetailsSelect) BoolX(ctx context.Context) bool {
	v, err := nds.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (nds *NodeDetailsSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := nds.sql.Query()
	if err := nds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
